[versions]
accompanistPager = "0.28.0"
activityCompose = "1.9.0"
androidplotCore = "1.5.10"
cardview = "1.0.0"
commonsCsv = "1.7"
composeThemeAdapter = "1.2.1"
compose = "1.6.7"
constraintlayout = "2.1.4"
coreKtx = "1.13.1"
coreTesting = "2.2.0"
espressoCore = "3.5.1"
flexbox = "3.0.0"
fragmentKtx = "1.7.1"
hilt = "2.51.1"
hiltAndroidGradlePlugin = "2.44"
hiltNavigationCompose = "1.2.0"
hiltWork = "1.2.0"
junitKtx = "1.1.5"
kotlinGradlePlugin = "1.8.10"
kotlinReflect = "1.9.20"
kotlinxCoroutines = "1.7.3"
legacySupportV4 = "1.0.0"
lifecycleExtensions = "2.2.0"
lifecycleLivedataKtx = "2.8.0"
lifecycleRuntimeCompose = "2.8.0"
lifecycleViewmodelCompose = "2.8.0"
material = "1.12.0"
composeMaterial = "1.6.7"
mockitoKotlin = "2.2.0"
moshiKotlin = "1.14.0"
navigationSafeArgsGradlePlugin = "2.7.7"
navigationUiKtx = "2.7.7"
recyclerview = "1.3.2"
room = "2.6.1"
runner = "1.5.2"
runtimeLivedata = "1.6.7"
threetenabp = "1.2.1"
threetenbp = "1.6.9"
junit = "4.13.2"
timber = "5.0.1"
workRuntimeKtx = "2.9.0"
kotlin = "1.9.24"
android = "8.4.0"

[plugins]
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
com-android-library = { id = "com.android.library", version.ref = "android" }
com-android-application = { id = "com.android.application", version.ref = "android" }

[libraries]
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }
androidplot-core = { module = "com.androidplot:androidplot-core", version.ref = "androidplotCore" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
compose-theme-adapter = { module = "com.google.android.material:compose-theme-adapter", version.ref = "composeThemeAdapter" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationUiKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "commonsCsv" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitKtx" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiKotlin" }
navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePlugin" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }
threetenbp = { module = "org.threeten:threetenbp", version.ref = "threetenbp" }
junit = { module = "junit:junit", version.ref = "junit" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
