[versions]
androidplotCore = "1.5.11"
appcompat = "1.7.1"
commonsCsv = "1.14.1"
compose = "1.10.0-rc01"
datastore = "1.2.0"
kotlinxCollectionsImmutable = "0.4.0"
material-icons-core = "1.7.8"
composeMaterial3 = "1.4.0"
coreKtx = "1.17.0"
coreTesting = "2.2.0"
espressoCore = "3.7.0"
hilt = "2.57.2"
androidxHilt = "1.3.0"
junitKtx = "1.3.0"
kotlinGradlePlugin = "2.2.21"
kotlinxCoroutines = "1.10.2"
luakJvm = "3.4.0"
material = "1.13.0"
mockitoCore = "5.20.0"
mockitoKotlinVersion = "6.1.0"
multiplatformMarkdownRenderer = "0.38.1"
coil = "3.3.0"
room = "2.8.3"
shot = "6.1.0"
test-runner = "1.7.0"
threetenabp = "1.4.9"
threetenbp = "1.7.2"
junit = "4.13.2"
timber = "5.0.1"
workRuntimeKtx = "2.11.0"
kotlin = "2.2.21"
android = "8.10.1"
ksp = "2.2.21-2.0.4"
hiltAndroidGradlePlugin = "2.57.2"
reorderable = "3.0.0"
glance = "1.1.1"
nav3Core = "1.0.0-rc01"
kotlinxSerializationCore = "1.9.0"
kotlinSerialization = "2.2.21"
semver = "3.0.0"

# Gradle script versions
buildJdk = "21"
jdk = "17"
androidSdk = "36"
minSdk = "24"
targetSdk = "35"
rules = "1.7.0"
uiautomator = "2.3.0"

[plugins]
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
com-android-library = { id = "com.android.library", version.ref = "android" }
com-android-application = { id = "com.android.application", version.ref = "android" }
com-google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android-gradle-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroidGradlePlugin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization"}

[libraries]
androidplot-core = { module = "com.androidplot:androidplot-core", version.ref = "androidplotCore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-material-icons = { module = "androidx.compose.material:material-icons-core", version.ref = "material-icons-core" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "commonsCsv" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxHilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxHilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitKtx" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
luak-jvm = { module = "com.soywiz.korlibs.luak:luak-android", version.ref = "luakJvm" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlinVersion" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoCore" }
multiplatform-markdown-renderer = { module = "com.mikepenz:multiplatform-markdown-renderer", version.ref = "multiplatformMarkdownRenderer" }
multiplatform-markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "multiplatformMarkdownRenderer" }
multiplatform-markdown-renderer-coil3 = { module = "com.mikepenz:multiplatform-markdown-renderer-coil3", version.ref = "multiplatformMarkdownRenderer" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
runner = { module = "androidx.test:runner", version.ref = "test-runner" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
shot = { module = "com.karumi:shot", version.ref = "shot" }
threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }
threetenbp = { module = "org.threeten:threetenbp", version.ref = "threetenbp" }
junit = { module = "junit:junit", version.ref = "junit" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
glance-appwidget-preview = { module = "androidx.glance:glance-appwidget-preview", version.ref = "glance" }
glance-preview = { module = "androidx.glance:glance-preview", version.ref = "glance" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "nav3Core" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationCore" }
shot-android = { module = "com.karumi:shot-android", version.ref = "shot" }
semver = { module = "io.github.z4kn4fein:semver", version.ref = "semver" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
